kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testoperator
subjects:
- kind: ServiceAccount
  name: testoperator
roleRef:
  kind: Role
  name: testoperator
  apiGroup: rbac.authorization.k8s.io
